spring:
  application:
    name: microservice-resourceservice
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_KEY_ACCESS}
