server:
  port: ${SERVER_PORT}
  error:
    include-stacktrace: never

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ${ROUTES_AUTH_SERVICE_ID}
          uri: ${ROUTES_AUTH_SERVICE_URI}
          predicates:
            - ${ROUTES_AUTH_SERVICE_PREDICATE}
          filters:
            - StripPrefix=1
            - PrefixPath=/ru-spshop-auth
        #----------------------------
        - id: ${ROUTES_RESOUSCE_SERVICE_ID}
          uri: ${ROUTES_RESOUSCE_SERVICE_URI}
          predicates:
            - ${ROUTES_RESOUSCE_SERVICE_PREDICATE}
          filters:
            - StripPrefix=1
            - PrefixPath=/ru-spshop-resource
            - JwtFilter

logging:
  level:
    root: INFO
    org.springframework.cloud: INFO
    org.springframework.web: INFO

jwt:
  secret: ${JWT_KEY_SECRET}

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: gateway