server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: http://localhost:8000/
          predicates:
            - Path=/**
        - id: ResourceService
          uri: http://localhost:8082/
          predicates:
            - Path=/**
